#!/bin/sh

# Recompile
cd "$(cat xmonad_source_dir_path)" && (stack install || exit 1)

# Create a hard link at the requested destination, replacing any existing one.
ln -f -T "$(stack exec -- which xmonad)" "${1}"
